// <auto-generated />
using EFCoreRPGEntities.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreRPGEntities.Migrations
{
    [DbContext(typeof(GameContext))]
    [Migration("20260505004457_AbilitiesUpdate")]
    partial class AbilitiesUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AbilityCharacter", b =>
                {
                    b.Property<int>("AbilitiesId")
                        .HasColumnType("int");

                    b.Property<int>("CharactersId")
                        .HasColumnType("int");

                    b.HasKey("AbilitiesId", "CharactersId");

                    b.HasIndex("CharactersId");

                    b.ToTable("CharacterAbilities", (string)null);
                });

            modelBuilder.Entity("EFCoreRPGEntities.Models.Abilities.Ability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AbilityLevel")
                        .HasColumnType("int");

                    b.Property<int>("Damage")
                        .HasColumnType("int");

                    b.Property<int>("DefenseModifier")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<int>("HealthModifier")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StrengthModifier")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Abilities");

                    b.HasDiscriminator().HasValue("Ability");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EFCoreRPGEntities.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Characters");

                    b.HasDiscriminator().HasValue("Character");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EFCoreRPGEntities.Models.Items.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArmorId")
                        .HasColumnType("int");

                    b.Property<int?>("WeaponId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArmorId");

                    b.HasIndex("WeaponId");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("EFCoreRPGEntities.Models.Items.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasDiscriminator().HasValue("Item");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EFCoreRPGEntities.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EastRoomId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NorthRoomId")
                        .HasColumnType("int");

                    b.Property<int?>("SouthRoomId")
                        .HasColumnType("int");

                    b.Property<int?>("WestRoomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EastRoomId");

                    b.HasIndex("NorthRoomId")
                        .IsUnique()
                        .HasFilter("[NorthRoomId] IS NOT NULL");

                    b.HasIndex("SouthRoomId")
                        .IsUnique()
                        .HasFilter("[SouthRoomId] IS NOT NULL");

                    b.HasIndex("WestRoomId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("EFCoreRPGEntities.Models.Abilities.MonsterAbility", b =>
                {
                    b.HasBaseType("EFCoreRPGEntities.Models.Abilities.Ability");

                    b.HasDiscriminator().HasValue("MonsterAbility");
                });

            modelBuilder.Entity("EFCoreRPGEntities.Models.Abilities.PlayerAbility", b =>
                {
                    b.HasBaseType("EFCoreRPGEntities.Models.Abilities.Ability");

                    b.Property<int>("Uses")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("PlayerAbility");
                });

            modelBuilder.Entity("EFCoreRPGEntities.Models.Monster", b =>
                {
                    b.HasBaseType("EFCoreRPGEntities.Models.Character");

                    b.Property<int>("AggressionLevel")
                        .HasColumnType("int");

                    b.HasIndex("RoomId");

                    b.HasDiscriminator().HasValue("Monster");
                });

            modelBuilder.Entity("EFCoreRPGEntities.Models.Player", b =>
                {
                    b.HasBaseType("EFCoreRPGEntities.Models.Character");

                    b.Property<int?>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.HasIndex("EquipmentId")
                        .IsUnique()
                        .HasFilter("[EquipmentId] IS NOT NULL");

                    b.HasIndex("RoomId");

                    b.HasDiscriminator().HasValue("Player");
                });

            modelBuilder.Entity("EFCoreRPGEntities.Models.Items.Armor", b =>
                {
                    b.HasBaseType("EFCoreRPGEntities.Models.Items.Item");

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Armor");
                });

            modelBuilder.Entity("EFCoreRPGEntities.Models.Items.Consumable", b =>
                {
                    b.HasBaseType("EFCoreRPGEntities.Models.Items.Item");

                    b.Property<int>("Effect")
                        .HasColumnType("int");

                    b.Property<int>("EffectStrength")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Consumable");
                });

            modelBuilder.Entity("EFCoreRPGEntities.Models.Items.Weapon", b =>
                {
                    b.HasBaseType("EFCoreRPGEntities.Models.Items.Item");

                    b.Property<int>("AttackPower")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Weapon");
                });

            modelBuilder.Entity("AbilityCharacter", b =>
                {
                    b.HasOne("EFCoreRPGEntities.Models.Abilities.Ability", null)
                        .WithMany()
                        .HasForeignKey("AbilitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCoreRPGEntities.Models.Character", null)
                        .WithMany()
                        .HasForeignKey("CharactersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFCoreRPGEntities.Models.Items.Equipment", b =>
                {
                    b.HasOne("EFCoreRPGEntities.Models.Items.Item", "Armor")
                        .WithMany()
                        .HasForeignKey("ArmorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EFCoreRPGEntities.Models.Items.Item", "Weapon")
                        .WithMany()
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Armor");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("EFCoreRPGEntities.Models.Room", b =>
                {
                    b.HasOne("EFCoreRPGEntities.Models.Room", "EastRoom")
                        .WithMany()
                        .HasForeignKey("EastRoomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EFCoreRPGEntities.Models.Room", "NorthRoom")
                        .WithOne()
                        .HasForeignKey("EFCoreRPGEntities.Models.Room", "NorthRoomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EFCoreRPGEntities.Models.Room", "SouthRoom")
                        .WithOne()
                        .HasForeignKey("EFCoreRPGEntities.Models.Room", "SouthRoomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EFCoreRPGEntities.Models.Room", "WestRoom")
                        .WithMany()
                        .HasForeignKey("WestRoomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EastRoom");

                    b.Navigation("NorthRoom");

                    b.Navigation("SouthRoom");

                    b.Navigation("WestRoom");
                });

            modelBuilder.Entity("EFCoreRPGEntities.Models.Monster", b =>
                {
                    b.HasOne("EFCoreRPGEntities.Models.Room", "Room")
                        .WithMany("Monsters")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Room");
                });

            modelBuilder.Entity("EFCoreRPGEntities.Models.Player", b =>
                {
                    b.HasOne("EFCoreRPGEntities.Models.Items.Equipment", "Equipment")
                        .WithOne("Player")
                        .HasForeignKey("EFCoreRPGEntities.Models.Player", "EquipmentId");

                    b.HasOne("EFCoreRPGEntities.Models.Room", "Room")
                        .WithMany("Players")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Equipment");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("EFCoreRPGEntities.Models.Items.Equipment", b =>
                {
                    b.Navigation("Player")
                        .IsRequired();
                });

            modelBuilder.Entity("EFCoreRPGEntities.Models.Room", b =>
                {
                    b.Navigation("Monsters");

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
